---
sudo: required
language: python
python:
  - "3.6"
  # - "2.7"
env:
  - MOLECULE_SCENARIO=centos74-goss
  - MOLECULE_SCENARIO=centos74-testinfra
  - MOLECULE_SCENARIO=ubuntu1804-goss
  - MOLECULE_SCENARIO=ubuntu1804-testinfra
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - virtualenv --python=$(which python3.6) envmolecule
  # - virtualenv --python=$(which python2.7) envmolecule
  - source envmolecule/bin/activate
  - pip install -r requirements.txt
  - curl -fsSL https://goss.rocks/install | sudo sh
script:
  - molecule --version
  - goss --version
  # - molecule lint --scenario-name ${MOLECULE_SCENARIO}
  # - molecule destroy --scenario-name ${MOLECULE_SCENARIO}
  # - molecule dependency --scenario-name ${MOLECULE_SCENARIO}
  # - molecule syntax --scenario-name ${MOLECULE_SCENARIO}
  # - molecule create --scenario-name ${MOLECULE_SCENARIO}
  # - molecule prepare --scenario-name ${MOLECULE_SCENARIO}
  # - molecule converge --scenario-name ${MOLECULE_SCENARIO}
  # - molecule side-effect --scenario-name ${MOLECULE_SCENARIO}
  # - molecule verify --scenario-name ${MOLECULE_SCENARIO}
  # - molecule destroy --scenario-name ${MOLECULE_SCENARIO}
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
