---
version: 1.0.{build}
branches:
  # whitelist
  only:
    - appveyorbr
image:
  - ubuntu1804
environment:
  - distribution: ubuntu
    init: /lib/systemd/systemd
    version: 1804
    # run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
services:
  - docker
install:
build_script:
test_script:
# test scripts must be here
# build: off
